name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build_and_release:
    name: xorg-xhost-static
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
            docker run --rm --volume="${{ github.workspace }}:/root:rw" alpine:latest /root/build-alpine.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: xorg-xhost-static-v*.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
